import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {Display} from "next/dist/compiled/@next/font";

const roboto = Roboto({
  adjustFontFallback: false,
  display: "auto",
  fallback: [],
  preload: false,
  style: "normal",
  weight: "400",
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
